@host=https://localhost:7071

GET {{host}}/Dinner

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZmUyNjg4Mi0wYjYwLTQ1ZGUtYTg2MS1mMWFiMDkxODZkMTQiLCJnaXZlbl9uYW1lIjoidHJ1b25nIiwiZmFtaWx5X25hbWUiOiJuZ3V5dWVuIiwianRpIjoiZTFiY2YwZTQtZjVlMS00MGNiLTkxZDEtNTg4ZWY4OTkyZDk3IiwiZXhwIjoxNjg1MzU5Mzc2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.-aKed-QmXaD-3n-pSLogBnbXyVBJmgOKPzR4A8YkNeg