@host=https://localhost:7071

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "truongtrongnguyen@gmail.com",
    "password": "12123"
}