@host=https://localhost:7071

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "truongtrong",
    "lastName": "nguyen",
    "email": "asdasdas@gmail.com",
    "password": "12123"
}